artifacts:
  ARTIFACTS_DIR: artifacts

data:
  # Data paths
  DATA_DIR: data
  TRAIN_DATA_PATH: data/train.csv
  TEST_DATA_PATH: data/test.csv
  PROCESSED_DATA_DIR: data/processed

  # Data processing parameters
  MAX_LEN_TEXT: 50
  MAX_LEN_CONTEXT: 20
  VOCAB_SIZE: 5000
  RANDOM_STATE: 42
  TRAIN_TEST_SPLIT: 0.2

model:
  # Model architecture
  MODEL_TYPE: "cnn_lstm"  # Options: "lstm_only", "cnn_lstm"

  # Word embeddings
  EMBEDDING_TYPE: "pretrained"  # Options: "pretrained", "scratch"
  EMBEDDING_DIM: 100
  PRETRAINED_EMBEDDINGS_PATH: "embeddings/glove.6B.100d.txt"

  # LSTM parameters
  HIDDEN_DIM: 128
  NUM_LAYERS: 1
  BIDIRECTIONAL: false
  DROPOUT: 0.3

  # CNN parameters (for CNN-LSTM model)
  CNN_FILTER_SIZES: [2, 3, 4]
  CNN_NUM_FILTERS: 64

  # Attention mechanism
  USE_ATTENTION: false

training:
  # Training parameters
  BATCH_SIZE: 32
  LEARNING_RATE: 0.001
  NUM_EPOCHS: 10
  OPTIMIZER: "adam"
  LOSS_FUNCTION: "cross_entropy"

  # Early stopping
  EARLY_STOPPING: true
  PATIENCE: 3

  # Class weights for imbalanced data
  CLASS_WEIGHTS: null  # Will be calculated automatically if needed

evaluation:
  # Evaluation metrics
  METRICS: ["accuracy", "f1_score", "precision", "recall"]

experiments:
  # Experiment configurations
  EXPERIMENT_NAMES: [
    "pretrained_no_attn",
    "pretrained_attn",
    "scratch_no_attn",
    "scratch_attn"
  ]